name: Deploy on push

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
     - name: Correction key
       run: sshpass -p${{ secrets.MDP }} ssh -o StrictHostKeyChecking=accept-new etu724@51.210.13.26 "cd .ssh && chmod g-rwx id_rsa"
     - name: Pull
       run: sshpass -p${{ secrets.MDP }} ssh -o StrictHostKeyChecking=accept-new etu724@51.210.13.26 "cd end-project-A3-Web/ && git pull"
